import { Inject, Injectable, InternalServerErrorException, NotFoundException } from "@nestjs/common";
import type { SupabaseClient } from "@supabase/supabase-js";
import { SUPABASE_ADMIN_CLIENT } from "../supabase/supabase.constants";
import PDFDocument from "pdfkit";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { Response } from "express";

@Injectable()
export class PaperExportService {
  constructor(
    @Inject(SUPABASE_ADMIN_CLIENT)
    private readonly supabaseAdminClient: SupabaseClient
  ) {}

  async generatePdf(paperId: string, institutionId: string, res: Response) {
    const { data: paper, error } = await this.supabaseAdminClient
      .from("institution_papers")
      .select("*, template:institution_templates(*), institution:institutions(*)")
      .eq("id", paperId)
      .eq("institution_id", institutionId)
      .single();

    if (error || !paper) {
      throw new NotFoundException("Paper not found.");
    }

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=ExamPaper_${paper.id}.pdf`);

    doc.pipe(res);

    // Institution Branding
    const instName = paper.institution?.name || "ExamCraft Institution";
    doc.fontSize(20).text(instName, { align: "center" });
    doc.moveDown(0.5);
    
    // Exam Title & Metadata
    doc.fontSize(16).text(paper.title, { align: "center" });
    doc.moveDown();

    const metadataX = 50;
    const metadataY = doc.y;
    doc.fontSize(10);
    doc.text(`Duration: ${paper.template?.duration_minutes || "N/A"} Minutes`, metadataX, metadataY);
    doc.text(`Total Marks: ${paper.template?.total_marks || "N/A"}`, metadataX + 250, metadataY, { align: "right" });
    doc.moveDown();
    
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Sections & Questions
    const metadata = paper.metadata as any;
    const sections = metadata.sections || [];

    sections.forEach((section: any, sIdx: number) => {
      doc.moveDown();
      doc.fontSize(12).text(`${section.title} (${section.marks} Marks)`, { underline: true });
      doc.moveDown(0.5);

      (section.questions || []).forEach((q: any, qIdx: number) => {
        const questionNum = `${sIdx + 1}.${qIdx + 1}`;
        doc.fontSize(11).text(`${questionNum}. ${q.title}`);
        
        if (q.metadata?.questionType === "mcq" && q.metadata?.mcqOptions?.length > 0) {
          doc.moveDown(0.3);
          const currentX = doc.x;
          q.metadata.mcqOptions.forEach((opt: any, optIdx: number) => {
             const letter = String.fromCharCode(97 + optIdx);
             doc.fontSize(10).text(`${letter}) ${opt.text}`, currentX + 20, doc.y);
          });
        }
        
        doc.moveDown(0.5);
      });
    });

    // Footer
    doc.fontSize(10).text(`Generated by ExamCraft - Your Institutional Paper Partner`, 50, 750, { align: "center" });

    doc.end();
  }

  async generateDocx(paperId: string, institutionId: string, res: Response) {
    const { data: paper, error } = await this.supabaseAdminClient
      .from("institution_papers")
      .select("*, template:institution_templates(*), institution:institutions(*)")
      .eq("id", paperId)
      .eq("institution_id", institutionId)
      .single();

    if (error || !paper) {
      throw new NotFoundException("Paper not found.");
    }

    const instName = paper.institution?.name || "ExamCraft Institution";
    const duration = paper.template?.duration_minutes || "N/A";
    const totalMarks = paper.template?.total_marks || "N/A";

    const docChildren: any[] = [
      new Paragraph({
        text: instName,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({
        text: paper.title,
        heading: HeadingLevel.HEADING_2,
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({
        children: [
          new TextRun({ text: `Duration: ${duration} Minutes`, bold: true }),
          new TextRun({ text: `\t\t\tTotal Marks: ${totalMarks}`, bold: true }),
        ],
      }),
      new Paragraph({ text: "" }) // Spacing
    ];

    const metadata = paper.metadata as any;
    const sections = metadata.sections || [];

    sections.forEach((section: any, sIdx: number) => {
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${section.title} (${section.marks} Marks)`, bold: true, underline: {} }),
          ],
        }),
        new Paragraph({ text: "" })
      );

      (section.questions || []).forEach((q: any, qIdx: number) => {
        const questionNum = `${sIdx + 1}.${qIdx + 1}`;
        docChildren.push(
          new Paragraph({
            text: `${questionNum}. ${q.title}`,
          })
        );
        
        if (q.metadata?.questionType === "mcq" && q.metadata?.mcqOptions?.length > 0) {
          q.metadata.mcqOptions.forEach((opt: any, optIdx: number) => {
             const letter = String.fromCharCode(97 + optIdx);
             docChildren.push(
               new Paragraph({
                 text: `   ${letter}) ${opt.text}`,
               })
             );
          });
        }
        docChildren.push(new Paragraph({ text: "" }));
      });
    });

    const doc = new Document({
      sections: [{
        properties: {},
        children: docChildren,
      }],
    });

    const b64string = await Packer.toBase64String(doc);
    const buffer = Buffer.from(b64string, "base64");

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", `attachment; filename=ExamPaper_${paper.id}.docx`);
    res.send(buffer);
  }
}


