export enum AuditAction {
  // Auth
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  // Users
  USER_INVITED = "USER_INVITED",
  USER_UPDATED = "USER_UPDATED",
  USER_ROLE_CHANGED = "USER_ROLE_CHANGED",
  USER_REMOVED = "USER_REMOVED",
  // Questions
  QUESTION_CREATED = "QUESTION_CREATED",
  QUESTION_UPDATED = "QUESTION_UPDATED",
  QUESTION_DELETED = "QUESTION_DELETED",
  QUESTION_APPROVED = "QUESTION_APPROVED",
  QUESTION_REJECTED = "QUESTION_REJECTED",
  // Papers
  PAPER_CREATED = "PAPER_CREATED",
  PAPER_STATUS_CHANGED = "PAPER_STATUS_CHANGED",
  PAPER_APPROVED = "PAPER_APPROVED",
  PAPER_REJECTED = "PAPER_REJECTED",
  PAPER_EXPORTED = "PAPER_EXPORTED",
  // Templates
  TEMPLATE_CREATED = "TEMPLATE_CREATED",
  TEMPLATE_UPDATED = "TEMPLATE_UPDATED",
  TEMPLATE_DELETED = "TEMPLATE_DELETED",
  // Settings
  PERMISSION_CHANGED = "PERMISSION_CHANGED",
}
